#!/bin/bash

# get the haplotig list from curated.contig_associations.log generated by purge_haplotigs

log=curated.contig_associations.log

# fist split the log file by blank lines

awk -v PATTERN="Primary_contig_%d.txt" 'BEGIN {n=1; FILE=sprintf(PATTERN, n)} !NF {n++; FILE=sprintf(PATTERN, n); next} {print > FILE}' $log

# then parse each primary-haplotig file

ls Primary_contig_*.txt > names.txt

for name in $(cat names.txt)
do
   head -1 $name | cut -d ',' -f 1 > $name.contig
   head -1 $name | cut -d ',' -f 2 | cut -d ' ' -f 1 > $name.tag
   head -1 $name | cut -d ',' -f 2 | cut -d ' ' -f 3 >> $name.contig
   head -1 $name | cut -d ',' -f 3 >> $name.tag
   tail -n +2 $name | cut -d ',' -f 2 >> $name.tag
   tail -n +2 $name | cut -d ',' -f 1 | cut -d '-' -f 2 | cut -d ' ' -f 2 >> $name.contig
   paste $name.contig $name.tag > $name.ct
   rm $name.contig $name.tag
done

ls *.ct > names.txt

for name in $(cat names.txt)
do
    Rscript bin/reshape.R $name $name.reshape.txt
done

cat *.reshape.txt > haplotig_list.txt

rm Primary_contig_* names*
